### ISSUE TITLE
Streamline Setup Screen

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#16]
Would it be possible to make the setup quicker, by adding a set of radio buttons to the **Upload Your sgRNA Library File** in the screen setup section ? That would remove the need for users to download a file from the server then to upload it back to the same server again for datasets using the common screening libraries. It would also allow values to settings like **Gene Identifier for non-targeting control(s)** to be set to suitable defaults by the application. Otherwise, biologists will need to extract the controls from the design spreadsheet and make them comma-separated, which could take time, depending on their programming skill.

**Comment by jwinter6** [comment]
Hi Dario,
That's a good point.
I am already working on this for the next major update since a couple of people mentioned this.
I plan also to bring defaults for all addgene available pooled libraries.

Best
Jan

Am 17. M?rz 2017 03:00:22 schrieb DarioS <notifications@github.com>:

Would it be possible to make the setup quicker, by adding a set of radio buttons to the Upload Your sgRNA Library File in the screen setup section ? That would remove the need for users to download a file from the server then to upload it back to the same server again for datasets using the common screening libraries. It would also allow values to settings like Gene Identifier for non-targeting control(s) to be set to suitable defaults by the application. Otherwise, biologists will need to extract the controls from the design spreadsheet and make them comma-separated, which could take time, depending on their programming skill.

-

**Comment by jecorn** [comment]
Along these lines, would it be possible to allow users to enter their own regex for custom library definition files? (rather than choosing from a drop-down)

**Comment by jwinter6** [comment]
Hi Jacob,

you can delete the entries in the dropdown menu - and enter your own.
This can be done for FASTA and FASTQ regular expression.

![ca_userregex](https://cloud.githubusercontent.com/assets/7203572/24725378/0362a4f8-1a4f-11e7-8f6a-7fc064a976e7.gif)

Is this what you refer to?

Best
Jan

**Comment by DarioS** [comment]
Currently for GeCKO V2, it's necessary to process Library A files, get a set of count files and evaluate QC metrics, process Library B files, get a second set of count files and evaluate QC metrics, concatenate the libraries using the command line, upload the concatenated count files to CRISPRAnalyzeR and then at last do tasks like differential expression analysis. This could be streamlined by specially handling A and B library files for this screen to avoid having to merge files outside of the application.

**Comment by jwinter6** [comment]
added in V1.20
