### ISSUE TITLE
Analysis without biological replicate

### ISSUE THREAD

**Issue by deb-m** [boutroslab/CRISPRAnalyzeR#33]
Unfortunately, I am trying to analyse a GeCKO result without any biological replicates. The analysis is quitting as edgeR has a strict 2 biological replicate requirement. Is there a way to switch off edgeR during analysis? I tried to work around the problem, by uploading duplicated readcount files (with different names), this time the analysis failed at DESeq2. Any workaround?

**Comment by jwinter6** [comment]
Hi Deb,

I am sorry but having only a single replicate for both conditions is currently not supported as this might confuse people and lead to analysis issues.
Since CRISPRAnalyzeR checks the uploaded data, it recognizes both files being identical in regards of the variation. Both DESeq2 and edgeR force people to use replicates and I cannot circumvent this.

Please note that running an analysis on samples without replicate cannot allow you any good information in regards to the screen itself or its performance.
For that, I kind of force the users to at least have two biological replicates for the treated group.

Cheers
Jan

**Comment by deb-m** [comment]
Hi Jan,

Thank you for your explanation. These were initial experiments, performed to see if there is any difference under treatment condition- not very useful. I have used mageck on them though, and got the readcount statistics to find out there was a terrible skew in the sgRNA representation
in the untreated control. 

This not directly related to CRISPRAnalyzeR, but would like to have your input, as you may have experience. We are using a full illumina lane for 5 samples using the brunello library. We are getting ~25 mil reads per sample, that is around 300X sequencing depth. I feel a 100X sequencing depth is sufficient for the analysis, or am I wrong? If we reduce depth of coverage, we can include more samples per lane, reducing cost.

Thanks again.
Deb

**Comment by jwinter6** [comment]
Hi Deb,

please send me an email to jan.winter@dkfz-heidelberg.de for further discussions, I am glad to share my knowledge with other CRISPR screeners :)

Best
Jan
