### ISSUE TITLE
Stuck at Converting Gene Identifiers

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#9]
Although I chose HGNC symbol as the identifier used in the guide RNA file and also as the identifier I'd like CRISPRAnalyzeR to use for its analysis, the processing in the Set Analysis Parameters section is stuck at the identifier conversion stage. Since this is no-op, I'd expect it to skipped almost immediately.

**Comment by jwinter6** [comment]
Hi Dario,
I thought this is fixed in the latest version 1.10.
If you are running version 1.10, could you do me favor and send me the log files?

please run the docker with the following parameters:

`
docker run --rm -v *LOGFOLDER*:/srv/shiny-server/CRISPRAnalyzeR/log -p 80:3838 boutroslab/crispranalyzer:latest
`

then access the logfolder that you set and send me the logs (via mail to jan.winter@dkfz-heidelberg.de):

fastq_extraction.log
analysis.log

This would help me a lot in finding this weird behaviour.
As you state, it skips the gene conversion, so progress bar information is a bit misleading.

Thanks for your help
Jan

**Comment by DarioS** [comment]
I am using version 1.10. I couldn't reproduce this problem today using a locally running version or the online version.
